<?php
require __DIR__ . '/../../inc/config_helpers.php';
require __DIR__ . '/../../inc/site.php';
$title = 'Données RE2020 en open data : l’Observatoire devient accessible à tous';
$description = 'Depuis septembre 2026, le ministère rend publiques les données de l’Observatoire RE2020 : bâtiments achevés, performances énergie-carbone et nouveaux usages pour la filière.';
$canonical = 'https://r-e-2020.fr/actualites/donnees-re2020-open-data-observatoire-2026/';
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= h($title) ?> | Actualités RE2020</title><meta name="description" content="<?= h($description) ?>"><link rel="canonical" href="<?= h($canonical) ?>"><link rel="stylesheet" href="/assets/css/app.css?v=4"><link rel="stylesheet" href="/assets/css/dossiers.css?v=2"><link rel="stylesheet" href="/assets/css/commercial.css?v=2"><link rel="stylesheet" href="/assets/css/theme.css?v=1"><link rel="stylesheet" href="/assets/css/identity.css?v=1"><script type="application/ld+json"><?= json_encode(['@context'=>'https://schema.org','@type'=>'NewsArticle','headline'=>$title,'description'=>$description,'datePublished'=>'2026-09-10','mainEntityOfPage'=>$canonical,'publisher'=>['@type'=>'Organization','name'=>'Keeplanet','url'=>'https://r-e-2020.fr/']],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) ?></script></head><body>
<header class="site-header"><div class="topbar"><div class="container topbar-inner"><span>Keeplanet · Bureau d’études thermiques qualifié OPQIBI</span><a href="tel:0806110559">0806 110 559</a></div></div><div class="container nav-wrap"><a class="brand" href="/"><span class="brand-text-logo"><span class="brand-text-main">r-e-2020</span><span class="brand-text-fr">.fr</span></span></a><nav class="main-nav"><a href="/tarifs-etude-thermique-re-2020/">Tarifs</a><a href="/dossiers-decryptages-re2020/">Dossiers</a><a href="/actualites/">Actualités</a><a href="/a-propos-keeplanet/">À propos</a><a href="/contact/">Contact</a></nav></div></header>
<main><article class="dossier-article"><header class="dossier-article-hero"><div class="container narrow"><div class="breadcrumbs"><a href="/">Accueil</a><span>›</span><a href="/actualites/">Actualités</a></div><span class="pill">Actualité</span><h1><?= h($title) ?></h1><p><?= h($description) ?></p><small>Publié le 10/09/2026</small></div></header><section class="section"><div class="container narrow article-body">
<p><strong>Une nouvelle source de données vient de s’ouvrir pour comprendre concrètement la RE2020.</strong> Le ministère de la Ville et du Logement a annoncé début septembre 2026 la mise à disposition en libre accès des données de l’Observatoire de la RE2020. Jusqu’ici surtout exploitées au travers d’analyses consolidées, ces informations peuvent désormais être réutilisées pour étudier les performances réellement atteintes par les constructions neuves.</p>
<p>Pour les maîtres d’ouvrage, bureaux d’études et concepteurs, l’intérêt est important : la réglementation ne se lit plus seulement à travers ses seuils théoriques. Les données issues des opérations achevées permettent aussi d’observer comment les projets se positionnent réellement en matière d’énergie, de carbone et de choix constructifs.</p>
<h2>Quelles données RE2020 sont désormais accessibles ?</h2>
<p>Le ministère précise que cette première mise à disposition concerne les <strong>opérations achevées ayant transmis leur déclaration attestant de la conformité des travaux</strong>. Elle couvre les maisons individuelles ou accolées, les logements collectifs, les bureaux ainsi que les établissements d’enseignement primaire et secondaire.</p>
<p>Les informations peuvent être analysées à plusieurs niveaux : projet, bâtiment, zone, groupe et composant. Elles sont accompagnées d’une documentation destinée à faciliter leur compréhension et leur réutilisation.</p>
<h2>Pourquoi cette ouverture est utile aux professionnels du bâtiment</h2>
<p>La RE2020 fixe des exigences sur la conception bioclimatique, les consommations d’énergie, l’impact carbone de l’énergie et de la construction ainsi que le confort d’été. Mais deux projets conformes peuvent présenter des profils très différents. L’ouverture des données permet de comparer les niveaux réellement obtenus et d’identifier progressivement les pratiques les plus courantes.</p>
<p>Pour un bureau d’études comme Keeplanet, ces données constituent surtout un outil de recul : elles permettent de confronter les résultats d’un projet à une population plus large, de suivre l’évolution des solutions techniques et de repérer les indicateurs qui deviennent les plus contraignants selon les typologies.</p>
<h2>Une donnée publique ne remplace pas l’étude thermique d’un projet</h2>
<p>Ces statistiques ne permettent pas de déduire qu’une solution technique sera conforme sur un nouveau bâtiment. Le <a href="/reglementaire/difference-cep-cepnr-calcul-re2020/">Cep et le Cep,nr</a>, le Bbio, les degrés-heures et les indicateurs carbone dépendent notamment de la géométrie, de l’orientation, de la zone climatique, des systèmes et des matériaux propres à chaque opération.</p>
<p>L’open data est donc un outil d’analyse et de comparaison, pas un raccourci vers la conformité. Le calcul réglementaire reste indispensable pour valider un projet précis.</p>
<h2>Un complément intéressant aux observatoires métiers</h2>
<p>Cette publication officielle complète les analyses réalisées à partir de données de terrain. Keeplanet publie par exemple son propre Observatoire à partir des études traitées par le bureau d’études. Les deux approches sont complémentaires : les données ministérielles reposent sur les opérations achevées et déclarées conformes, tandis que les données d’études permettent d’observer les projets plus tôt dans leur cycle de conception.</p>
<p>Cette distinction est utile pour suivre non seulement ce qui est finalement construit, mais aussi la manière dont les choix techniques évoluent avant le chantier.</p>
<h2>Vers une RE2020 davantage pilotée par le retour d’expérience</h2>
<p>Le ministère indique que l’objectif de cette ouverture est de renforcer la transparence, d’accompagner la montée en compétence de la filière et de préparer les prochains jalons de la réglementation. La publication intervient alors que plusieurs ajustements de la RE2020 sont déjà entrés en vigueur en 2026.</p>
<p>À mesure que le volume de projets achevés augmente, l’Observatoire devrait donc devenir une ressource de plus en plus utile pour mesurer les effets réels de la réglementation et objectiver les évolutions des pratiques constructives.</p>
<h2>Faire étudier un projet RE2020 avec Keeplanet</h2>
<p>Les données nationales donnent des repères ; la conformité se joue projet par projet. Keeplanet réalise les études énergétiques et environnementales RE2020, de la phase permis jusqu’aux éléments nécessaires à la fin de chantier. Pour un bâtiment collectif, tertiaire ou assimilé, consultez notre <a href="/tarifs-etude-thermique-re-2020/collectif-tertiaire/"><strong>prestation RE2020 collectif et tertiaire</strong></a>. Pour une maison ou une extension, retrouvez nos <a href="/tarifs-etude-thermique-re-2020/maison-individuelle-extensions/">offres RE2020 maison individuelle</a>.</p>
<div class="migration-note"><strong>Sources et vérification</strong><p>Source principale : <a href="https://www.ecologie.gouv.fr/presse/ministere-ville-du-logement-rend-publiques-donnees-re2020-accompagner-transition" rel="nofollow noopener" target="_blank">Ministère de la Ville et du Logement, communiqué publié le 3 septembre 2026</a>. Le portail RT-RE Bâtiment relaie cette publication dans ses actualités du 4 septembre 2026.</p></div>
<div class="related-resources"><strong>À lire aussi :</strong> <a href="/actualites/observatoire-re2020-keeplanet-1068-etudes-2e-trimestre-2026/">Observatoire Keeplanet T2 2026</a> · <a href="/reglementaire/acv-carbone-re2020-permis-construire/">ACV carbone RE2020</a> · <a href="/dossiers-decryptages-re2020/">Dossiers RE2020</a></div>
<div class="article-cta"><div><span class="eyebrow">Un projet RE2020 ?</span><h2>Faites valider votre projet par un thermicien.</h2><p>Maison, extension, collectif ou tertiaire : Keeplanet vous accompagne dans l’étude réglementaire.</p></div><a class="btn" href="/tarifs-etude-thermique-re-2020/">Voir nos prestations</a></div>
</div></section></article></main><footer class="site-footer"><div class="container footer-bottom"><span>© <?= date('Y') ?> r-e-2020.fr · Keeplanet</span><span><a href="/mentions-legales/">Mentions légales</a></span></div></footer></body></html>