<?php
/*
 * Corps éditoriaux des nouveaux dossiers publiés directement sur la version Git.
 * Séparé des contenus historiques importés de WordPress pour éviter d'écraser les migrations.
 */
return [
    'ponts-thermiques-re2020-ratio-psi-psi9' => <<<'HTML'
<p>Les ponts thermiques sont parfois traités comme un détail de calcul. En RE2020, ils font pourtant l’objet d’exigences réglementaires propres et peuvent dégrader directement la performance de l’enveloppe, le Bbio et la conformité globale du projet.</p>
<p>Deux valeurs doivent notamment être distinguées : le <strong>Ratio ψ</strong>, qui mesure le poids global des ponts thermiques rapporté à la surface de référence, et le <strong>Ψ9</strong>, qui vise spécifiquement les liaisons entre planchers intermédiaires et murs donnant sur l’extérieur ou un local non chauffé.</p>
<p>Voici comment les comprendre, quels seuils respecter et surtout comment éviter qu’un détail constructif mal anticipé ne complique l’étude RE2020.</p>
<h2>Que désigne un pont thermique en RE2020 ?</h2><p>Un pont thermique correspond à une zone de l’enveloppe où la continuité de l’isolation est perturbée. La chaleur y traverse plus facilement la paroi qu’en partie courante. Les liaisons plancher-façade, mur-mur, toiture-mur, plancher bas-mur ou encore certaines liaisons autour des baies peuvent ainsi générer des déperditions supplémentaires.</p><p>La FAQ officielle RE2020 n°017 précise que le calcul du ratio global prend en compte les ponts thermiques de liaison entre au moins deux parois lorsque l’une d’elles au moins est en contact avec l’extérieur ou un local non chauffé. Les ponts thermiques structurels intégrés directement dans une paroi ne relèvent pas de ce même calcul de ratio.</p>
<h2>Ratio ψ : le seuil global à ne pas dépasser</h2><p>L’article 22 de l’arrêté du 4 août 2021 fixe, dans le cas général visé par son II, un <strong>Ratio ψ maximal de 0,33 W/(m² Sref.K)</strong>. Cette valeur représente les déperditions liées à l’ensemble des ponts thermiques linéaires du bâtiment, rapportées à sa surface de référence.</p><p>Autrement dit, il ne suffit pas qu’une seule liaison soit performante : c’est la somme des coefficients linéiques, pondérés par leurs longueurs, qui compte dans le bilan global.</p>
<h2>Ψ9 : le point de vigilance des planchers intermédiaires</h2><p>La même disposition réglementaire impose également que le <strong>coefficient de transmission thermique linéique moyen Ψ9</strong> des liaisons entre les planchers intermédiaires et les murs donnant sur l’extérieur ou un local non chauffé n’excède pas <strong>0,60 W/(m.K)</strong>.</p>
<h2>Pourquoi les ponts thermiques influencent aussi le Bbio</h2><p>Les ponts thermiques augmentent les déperditions de l’enveloppe et peuvent pénaliser le <a href="/reglementaire/attestation-bbio-re2020-contenu-lien-bureau-etudes/">Bbio du projet</a>.</p>
<h2>Quels ponts thermiques faut-il traiter en priorité ?</h2><h3>Liaisons plancher intermédiaire / façade</h3><p>C’est le cas emblématique du Ψ9. Selon le système constructif, le traitement peut passer par une isolation thermique extérieure continue, des rupteurs de ponts thermiques, une conception structurelle spécifique ou un détail de liaison optimisé.</p><h3>Liaisons plancher bas / murs</h3><p>Vide sanitaire, dalle sur terre-plein ou sous-sol : la continuité de l’isolation au pied des murs doit être étudiée dès la conception.</p><h3>Liaisons toiture / murs et acrotères</h3><p>Les toitures-terrasses et acrotères sont des zones sensibles. Une isolation continue et un détail constructif cohérent évitent une concentration des pertes.</p><h3>Angles, refends et baies</h3><p>Les liaisons mur-mur, certains refends et les raccords murs-baies peuvent également entrer dans le calcul du ratio global.</p>
<h2>Rupteurs de ponts thermiques : utiles, mais pas automatiques</h2><p>Le rupteur n’est pas une obligation générale en tant que produit. La RE2020 impose un résultat, pas une technologie unique.</p>
<h2>Pourquoi anticiper ces valeurs avant le dépôt du permis ?</h2><p>Une étude RE2020 réalisée suffisamment tôt permet d’identifier les liaisons sensibles, de tester des solutions et de préserver une marge sur le Bbio. Cette logique rejoint celle de la <a href="/reglementaire/compacite-bati-re2020/">compacité du bâti</a>.</p>
<h2>Cas des extensions : attention aux exigences adaptées</h2><p>Les extensions et petites surfaces peuvent relever de dispositions adaptées. Consultez notre dossier sur les <a href="/reglementaire/extension-re2020-seuils-surface/">seuils et obligations RE2020 des extensions</a>.</p>
<h2>FAQ — Ponts thermiques et RE2020</h2><h3>Quel est le Ratio ψ maximal en RE2020 ?</h3><p>Dans le cas général du II de l’article 22 de l’arrêté du 4 août 2021, le ratio ne doit pas dépasser 0,33 W/(m² Sref.K).</p><h3>Quel est le seuil Ψ9 ?</h3><p>Le coefficient moyen des liaisons entre planchers intermédiaires et murs donnant sur l’extérieur ou un local non chauffé ne doit pas dépasser 0,60 W/(m.K).</p><h3>Un rupteur de pont thermique est-il obligatoire ?</h3><p>Non. La réglementation fixe des performances à respecter.</p>
<h2>Faire vérifier les ponts thermiques dans votre étude RE2020</h2><p>Chez Keeplanet, les thermiciens intègrent les caractéristiques de l’enveloppe, des liaisons et des systèmes constructifs dans l’étude réglementaire afin d’identifier les points qui pénalisent réellement le projet.</p><div class="article-cta"><div><strong>Besoin de sécuriser votre enveloppe RE2020 ?</strong><p>Faites analyser votre projet par les thermiciens Keeplanet.</p></div><a class="btn" href="/tarifs-etude-thermique-re-2020/">Voir les prestations RE2020</a></div><p><strong>Sources réglementaires :</strong> <a href="https://www.legifrance.gouv.fr/loda/id/JORFTEXT000043936431" rel="nofollow noopener" target="_blank">arrêté du 4 août 2021 — Légifrance</a>.</p>
HTML,
];