<?php
return [
're2020-tertiaire-specifique-hotels-commerces-industrie' => <<<'HTML'
<p>Depuis le <strong>1er mai 2026</strong>, le champ de la RE2020 s’est fortement élargi. Des bâtiments neufs qui relevaient encore auparavant de la RT2012 sont désormais soumis aux exigences énergétiques et environnementales de la RE2020 : hôtels, restaurants, commerces, crèches, établissements de santé, EHPAD, gymnases, bâtiments industriels ou artisanaux, aérogares et plusieurs autres usages.</p>
<p>Pour les maîtres d’ouvrage, architectes et entreprises, le changement est important : il ne s’agit plus seulement de vérifier une consommation conventionnelle. Le projet doit désormais intégrer les indicateurs RE2020, l’impact carbone de la construction, le confort d’été et les nouvelles obligations de contrôle prévues pour ces usages.</p>
<h2>Quels bâtiments tertiaires sont concernés par la RE2020 depuis le 1er mai 2026 ?</h2>
<p>Le décret n° 2026-16 du 15 janvier 2026 et l’arrêté du 19 mars 2026 ont étendu la RE2020 aux constructions neuves ou parties nouvelles relevant notamment des usages suivants :</p>
<ul><li>hôtels ;</li><li>restaurants ;</li><li>commerces ;</li><li>établissements d’accueil de la petite enfance, comme les crèches et haltes-garderies ;</li><li>bâtiments universitaires d’enseignement et de recherche et certains bâtiments d’enseignement atypiques ;</li><li>médiathèques et bibliothèques ;</li><li>établissements de santé et EHPAD ;</li><li>gymnases, salles de sport et vestiaires ;</li><li>bâtiments à usage industriel et artisanal ;</li><li>aérogares.</li></ul>
<p>Le critère essentiel est la <strong>date de dépôt de la demande de permis de construire ou de la déclaration préalable</strong> : pour ces usages, les dispositions s’appliquent aux demandes déposées à compter du 1er mai 2026.</p>
<h2>Que change concrètement le passage de la RT2012 à la RE2020 ?</h2>
<p>La RE2020 combine plusieurs dimensions. L’étude doit traiter la performance énergétique du bâtiment, sa conception bioclimatique, son comportement en période chaude et sa performance environnementale. Le carbone des produits de construction et équipements devient donc un sujet réglementaire à part entière via l’analyse de cycle de vie.</p>
<p>Pour un projet tertiaire, cela implique de travailler plus tôt sur les choix d’enveloppe, les systèmes de chauffage et de refroidissement, la ventilation, l’éclairage et les matériaux. Une solution satisfaisante du seul point de vue énergétique n’est pas nécessairement optimale une fois l’ACV intégrée.</p>
<h2>Un nouvel indicateur d’énergie renouvelable calculé à titre informatif</h2>
<p>Le décret de janvier 2026 introduit également le calcul, <strong>à titre informatif</strong>, de la consommation d’énergie primaire renouvelable du bâtiment. Elle couvre notamment le chauffage, le refroidissement, l’eau chaude sanitaire, l’éclairage, la mobilité interne et les auxiliaires concernés.</p>
<p>Cet indicateur ne doit pas être confondu avec le <a href="/reglementaire/difference-cep-cepnr-calcul-re2020/">Cep et le Cep,nr</a>. Il complète la lecture énergétique du projet sans constituer, dans le décret, une nouvelle exigence de résultat autonome à respecter.</p>
<h2>La perméabilité à l’air devient un point de contrôle pour ces bâtiments</h2>
<p>L’extension réglementaire ne concerne pas uniquement le calcul. Le portail officiel RT-RE Bâtiment précise que la <strong>mesure de la perméabilité à l’air</strong> ainsi que le respect d’une valeur maximale deviennent obligatoires pour ces bâtiments neufs, comme pour les usages déjà soumis à la RE2020.</p>
<p>Cette exigence renforce l’importance de la continuité de l’enveloppe et de la préparation du chantier. Les détails de mise en œuvre doivent être anticipés dès la conception afin d’éviter qu’un défaut d’étanchéité ne soit découvert au moment des contrôles.</p>
<h2>Quelles attestations faut-il prévoir ?</h2>
<p>Les bâtiments neufs concernés basculent également vers le dispositif d’<strong>attestations de respect de la RE2020</strong>, en remplacement des attestations RT2012. Le projet doit donc être organisé autour des différentes étapes réglementaires, depuis l’autorisation d’urbanisme jusqu’à l’achèvement des travaux.</p>
<p>Le bureau d’études doit disposer suffisamment tôt des plans, usages, surfaces, compositions de parois et systèmes envisagés pour établir une modélisation cohérente. Les modifications importantes en cours de conception ou de chantier doivent ensuite être répercutées dans l’étude.</p>
<h2>Pourquoi l’ACV devient-elle particulièrement importante en tertiaire ?</h2>
<p>Les bâtiments tertiaires et industriels peuvent comporter des structures, façades, équipements techniques et quantités de matériaux très différents d’un projet résidentiel. L’<a href="/reglementaire/acv-carbone-re2020-permis-construire/">ACV carbone RE2020</a> doit donc être intégrée comme un véritable outil de conception et non comme une vérification ajoutée à la fin.</p>
<p>La qualité des données environnementales compte également. Lorsque des FDES ou PEP spécifiques et valides existent, elles permettent de représenter plus précisément les produits et équipements réellement prévus. Notre dossier sur les <a href="/reglementaire/fdes-donnees-environnementales-acv-carbone/">FDES et données environnementales</a> détaille leur rôle dans le calcul.</p>
<h2>FAQ — RE2020 tertiaire spécifique</h2>
<h3>Un commerce neuf est-il désormais soumis à la RE2020 ?</h3><p>Oui, pour les demandes de permis de construire ou déclarations préalables déposées à compter du 1er mai 2026, sous réserve du champ d’application prévu par les textes.</p>
<h3>Les hôtels et restaurants sont-ils concernés ?</h3><p>Oui. Ils figurent explicitement parmi les usages ajoutés au périmètre de la RE2020 en 2026.</p>
<h3>Les bâtiments industriels et artisanaux passent-ils aussi en RE2020 ?</h3><p>Oui, les bâtiments à usage industriel et artisanal font partie des usages concernés par l’extension entrée en vigueur le 1er mai 2026.</p>
<h3>Une ACV est-elle nécessaire pour ces nouveaux usages ?</h3><p>La RE2020 évalue la performance environnementale des constructions concernées selon sa méthode réglementaire. Il faut donc anticiper les données nécessaires au calcul carbone en même temps que l’étude énergétique.</p>
<h3>Un projet déposé avant le 1er mai 2026 bascule-t-il automatiquement en RE2020 ?</h3><p>Le décret vise les demandes de permis de construire ou déclarations préalables déposées à compter du 1er mai 2026. La date de dépôt est donc déterminante pour l’application de cette extension.</p>
<h2>Faire réaliser une étude RE2020 pour un bâtiment tertiaire</h2>
<p>Keeplanet accompagne les projets collectifs et tertiaires dans les études énergétiques et environnementales RE2020, de la conception réglementaire à l’actualisation des choix techniques.</p>
<div class="article-cta"><div><strong>Hôtel, commerce, restaurant, crèche, santé, sport ou bâtiment industriel ?</strong><p>Faites analyser votre projet selon les exigences RE2020 applicables à son usage et à sa date de dépôt.</p></div><a class="btn" href="/tarifs-etude-thermique-re-2020/collectif-tertiaire/">Demander une étude collectif / tertiaire</a></div>
<p><strong>Sources principales :</strong> <a href="https://rt-re-batiment.developpement-durable.gouv.fr/re2020-extension-aux-batiments-tertiaires-a1227.html?lang=fr" rel="nofollow noopener" target="_blank">RT-RE Bâtiment — extension aux bâtiments tertiaires spécifiques et industriels/artisanaux</a> · <a href="https://www.legifrance.gouv.fr/loda/id/JORFTEXT000053378846/" rel="nofollow noopener" target="_blank">décret n° 2026-16 du 15 janvier 2026 — Légifrance</a>.</p>
HTML,
'verification-ventilation-re2020-protocole-fin-chantier' => <<<'HTML'
<p>En RE2020, une ventilation prévue dans l’étude thermique ne suffit pas : dans les bâtiments et parties de bâtiments à usage d’habitation, le système installé doit aussi être <strong>vérifié après travaux et ses performances mesurées</strong>. Cette exigence est prévue par l’article 20 de l’arrêté du 4 août 2021.</p>
<p>Une VMC correctement dimensionnée sur le papier peut présenter à la réception un défaut de raccordement, un débit insuffisant, une bouche inadaptée ou une installation différente de celle prise en compte dans l’étude. Anticiper le contrôle évite de découvrir ces écarts au moment de finaliser la conformité du bâtiment.</p>
<h2>Que demande exactement la RE2020 pour la ventilation ?</h2><p>L’article 20 impose, pour les bâtiments et parties de bâtiments à usage d’habitation, que tout système de ventilation soit vérifié afin de s’assurer de son bon fonctionnement. Ses performances doivent être mesurées par une personne reconnue compétente par le ministre chargé de la construction, selon les dispositions de l’annexe VIII et le protocole de vérification qui y est mentionné.</p>
<h2>Pourquoi la ventilation est-elle contrôlée en fin de chantier ?</h2><p>La ventilation renouvelle l’air intérieur, évacue l’humidité et les polluants et participe au fonctionnement énergétique du bâtiment. Une installation différente de l’hypothèse réglementaire peut créer un fonctionnement réel insuffisant et une incohérence entre le chantier et l’étude RE2020.</p>
<h2>Quels points faut-il sécuriser avant le contrôle ?</h2><h3>La conformité entre l’étude et le matériel installé</h3><p>Le type de ventilation retenu dans l’étude doit rester cohérent avec l’installation finale. Un changement de système ou de référence en cours de chantier doit être signalé au bureau d’études afin de vérifier son incidence sur le calcul.</p><h3>Les entrées d’air, bouches et réseaux</h3><p>Les composants doivent être présents, correctement positionnés et adaptés aux locaux concernés. Les réseaux doivent être raccordés sans défaut manifeste susceptible de réduire les débits.</p><h3>Le fonctionnement de l’installation</h3><p>Une installation alimentée mais mal réglée ne garantit pas les performances attendues. Les mesures servent à objectiver son fonctionnement réel.</p>
<h2>Ventilation et étude RE2020 : pourquoi éviter les changements de dernière minute ?</h2><p>La ventilation intervient dans le calcul énergétique. Le choix d’une <a href="/reglementaire/vmc-hygro-b-vs-double-flux-re2020/">VMC simple flux ou double flux</a>, ses caractéristiques et ses auxiliaires peuvent modifier les résultats. Remplacer une solution prévue sans mise à jour de l’étude peut donc créer une incohérence à la réception.</p>
<h2>Quelle différence avec le test d’étanchéité à l’air ?</h2><p>Le contrôle de la ventilation et la mesure de perméabilité de l’enveloppe sont distincts. La perméabilité concerne les infiltrations parasites ; la vérification de ventilation porte sur le renouvellement d’air organisé. En résidentiel, l’arrêté fixe notamment un Q4Pa-surf maximal de <strong>0,60 m³/(h.m²)</strong> en maison individuelle ou accolée et <strong>1,00 m³/(h.m²)</strong> en bâtiment collectif d’habitation. Retrouvez notre dossier sur le <a href="/reglementaire/controle-fin-chantier-etancheite-air-re2020/">contrôle de fin de chantier et l’étanchéité à l’air</a>.</p>
<h2>Comment préparer efficacement la fin de chantier ?</h2><p>Avant l’intervention, vérifiez que le système est terminé, alimenté, accessible et conforme aux choix communiqués au bureau d’études. Les modifications de références, réseaux ou systèmes doivent être intégrées dans la version finale de l’étude lorsque nécessaire.</p>
<h2>FAQ — Vérification de la ventilation RE2020</h2><h3>La vérification est-elle obligatoire en maison RE2020 ?</h3><p>Oui. L’article 20 prévoit la vérification du système et la mesure de ses performances dans les bâtiments et parties de bâtiments à usage d’habitation.</p><h3>Qui peut la réaliser ?</h3><p>Le texte prévoit une personne reconnue compétente par le ministre chargé de la construction, conformément au protocole applicable.</p><h3>Le bureau d’études thermique réalise-t-il forcément ce contrôle ?</h3><p>Non. L’étude réglementaire et les contrôles ou attestations de fin de chantier correspondent à des missions distinctes. Keeplanet peut fournir l’étude complète et les éléments nécessaires à l’opérateur chargé des vérifications finales.</p><h3>Que faire si la VMC a changé pendant le chantier ?</h3><p>Transmettez le changement au bureau d’études afin de vérifier si une mise à jour du calcul RE2020 est nécessaire.</p>
<h2>Sécuriser votre étude RE2020 jusqu’à la fin des travaux</h2><p>Keeplanet réalise les études énergétiques RE2020 et accompagne les projets dans la mise à jour des caractéristiques réellement mises en œuvre.</p><div class="article-cta"><div><strong>Votre projet approche de la fin des travaux ?</strong><p>Faites mettre à jour votre étude RE2020 et préparez les éléments nécessaires aux contrôles finaux.</p></div><a class="btn" href="/tarifs-etude-thermique-re-2020/">Voir les prestations RE2020</a></div>
<p><strong>Source principale :</strong> <a href="https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000043938747/" rel="nofollow noopener" target="_blank">article 20 de l’arrêté du 4 août 2021 — Légifrance</a>.</p>
HTML,
];