<?php
?>
<section class="hero commercial-hero">
  <div class="container hero-grid">
    <div class="hero-copy">
      <span class="eyebrow">Keeplanet · Bureau d’études thermiques qualifié OPQIBI</span>
      <h1>Votre étude RE2020, du permis jusqu’à la fin des travaux.</h1>
      <p class="hero-lead">Maison, extension, logement collectif ou bâtiment tertiaire : vous déposez vos pièces, nos thermiciens prennent en charge l’étude et vous retrouvez vos documents dans votre espace sécurisé.</p>
      <div class="hero-actions"><a class="btn" href="/tarifs-etude-thermique-re-2020/maison-individuelle-extensions/">Maison & extension</a><a class="btn btn-ghost" href="/tarifs-etude-thermique-re-2020/collectif-tertiaire/">Collectif & tertiaire</a></div>
      <div class="trust-line"><span>★★★★★</span><strong><?= h(google_rating_label()) ?>/5</strong><span>·</span><strong><?= h(projects_label()) ?>+ projets</strong><span>·</span><strong>OPQIBI 1331 & 1332</strong></div>
    </div>
    <aside class="hero-card proof-card">
      <div class="mini-label">Un bureau d’études vérifiable</div>
      <h2>Qualifications OPQIBI</h2>
      <p><strong>1331</strong> — Étude thermique réglementaire « maison individuelle »</p>
      <p><strong>1332</strong> — Étude thermique réglementaire « bâtiment collectif d’habitation et/ou tertiaire »</p>
      <a class="card-link" href="https://www.opqibi.com/fiche/3545" target="_blank" rel="noopener">Voir la fiche officielle OPQIBI →</a>
    </aside>
  </div>
</section>
<section class="metric-strip"><div class="container metrics"><div><strong><?= h(standard_delay_label()) ?></strong><span>délai actuel maison</span></div><div><strong><?= h(cfg('experience_years',16)) ?> ans</strong><span>d’expérience</span></div><div><strong><?= h(projects_label()) ?>+</strong><span>projets suivis</span></div><div><strong>France entière</strong><span>suivi en ligne</span></div></div></section>
<section class="section"><div class="container"><div class="section-head"><span class="eyebrow">Votre projet</span><h2>Deux parcours, une équipe technique.</h2><p>Le site vous oriente directement vers la bonne prestation sans vous faire parcourir toute la réglementation.</p></div><div class="cards two major-choices"><article class="card pricing-choice"><span class="card-kicker">Maison individuelle & extension</span><h2>Tarifs immédiats et packs lisibles</h2><p>Phase permis, étude thermique complète, ACV et accompagnement jusqu’à la fin des travaux.</p><ul><li>Pack Permis à <?= h(price_ttc_label('price_pack_permis_ttc')) ?></li><li>Étude complète dès <?= h(price_ttc_label('price_fin_travaux_ttc')) ?></li><li>Attestation Bbio – PCMI 14 selon formule</li></ul><a class="btn" href="/tarifs-etude-thermique-re-2020/maison-individuelle-extensions/">Voir les tarifs maison</a></article><article class="card pricing-choice dark-card"><span class="card-kicker">Collectif & tertiaire</span><h2>Une étude chiffrée selon l’opération</h2><p>Logements collectifs, bureaux, commerces, ERP et bâtiments tertiaires : cadrage technique puis devis adapté.</p><ul><li>Typologie et surfaces</li><li>Usages et zones thermiques</li><li>RE2020, ACV et variantes selon besoin</li></ul><a class="btn btn-white" href="/tarifs-etude-thermique-re-2020/collectif-tertiaire/">Préparer mon devis</a></article></div></div></section>
<section class="section soft"><div class="container split"><div><span class="eyebrow">Pourquoi Keeplanet</span><h2>Une étude réglementaire, avec un vrai suivi.</h2><p class="big-p">Les calculs ne sont qu’une partie du travail. Les choix d’enveloppe, de systèmes, de confort d’été et de données environnementales doivent rester cohérents jusqu’à la fin du projet.</p><div class="inline-links"><a href="/qualifications-assurances-garanties/">Qualifications & assurances →</a><a href="/exemples-livrables-re2020/">Voir les livrables →</a><a href="/questions-frequentes-re2020/">Questions fréquentes →</a></div></div><div class="check-list"><div><b>✓</b><span><strong>Qualifié OPQIBI</strong><small>1331 et 1332 vérifiables dans l’annuaire officiel</small></span></div><div><b>✓</b><span><strong>Assurance professionnelle</strong><small>activité couverte pour les études réalisées</small></span></div><div><b>✓</b><span><strong>Espace client sécurisé</strong><small>documents, messages et historique du dossier</small></span></div><div><b>✓</b><span><strong>Thermicien dédié</strong><small>conseils et variantes selon la formule choisie</small></span></div></div></div></section>
<section class="section"><div class="container"><div class="section-head row-head"><div><span class="eyebrow">Comprendre avant de décider</span><h2>Nos ressources RE2020.</h2></div><a class="btn btn-ghost" href="/dossiers-decryptages-re2020/">Tous les dossiers</a></div><div class="cards three"><article class="card article-card"><span class="pill">Réglementaire</span><h3>Attestation Bbio et permis de construire</h3><p>Ce qui est demandé au dépôt du permis et le rôle de l’étude thermique.</p><a href="/reglementaire/attestation-bbio-re2020-contenu-lien-bureau-etudes/">Lire le dossier →</a></article><article class="card article-card"><span class="pill">Calcul</span><h3>Bbio, Cep, Cep,nr et DH</h3><p>Comprendre les indicateurs qui structurent la conformité d’un projet.</p><a href="/reglementaire/difference-cep-cepnr-calcul-re2020/">Comprendre les indicateurs →</a></article><article class="card article-card"><span class="pill">Veille</span><h3>Actualités RE2020</h3><p>Suivez les évolutions des textes, du moteur de calcul et des données environnementales.</p><a href="/actualites/">Voir les actualités →</a></article></div></div></section>
<section class="keepote-block"><div class="container keepote-inner"><div class="keepote-visual"><img src="/assets/img/keepote-nu-assis-simple.png?v=6" width="360" height="360" alt="KeePote assis, assistant Keeplanet pour vos questions RE2020" loading="lazy"></div><div class="keepote-copy"><span class="eyebrow">KeePote · Assistant Keeplanet</span><h2>Besoin d’aide ? Demandez à KeePote.</h2><p>KeePote est l’assistant Keeplanet entraîné sur la RE2020 et notre documentation validée. Il peut vous orienter, expliquer les notions réglementaires et vous aider à comprendre les étapes de votre projet.</p><p class="keepote-human"><strong>Besoin d’un humain ?</strong> Nos thermiciens et l’équipe Keeplanet restent disponibles par téléphone, message ou depuis votre espace client.</p></div><button class="btn keepote-open" type="button" data-keepote-open onclick="document.querySelector('.ai-panel').hidden=false">Parler à KeePote</button></div></section>
<section class="cta-band"><div class="container cta-inner"><div><span class="eyebrow light">Prêt à lancer votre dossier ?</span><h2>Choisissez votre type de projet.</h2></div><div class="hero-actions"><a class="btn btn-white" href="/tarifs-etude-thermique-re-2020/maison-individuelle-extensions/">Maison & extension</a><a class="btn btn-white" href="/tarifs-etude-thermique-re-2020/collectif-tertiaire/">Collectif & tertiaire</a></div></div></section>